#!/usr/bin/env bash
# Kills the infinity and beyond progam using the kill signal

# Get the pid of the program
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Terminate the infinate process
if [ -n "$id" ]
then
	SIGKILL "$id"
fi
