#!/usr/bin/env bash
# This scripts will display "Best School" 10 times, "bad luck" on the 4th iteration, and "good luck on the 8th iteration

i=0

while [ $i -lt 10 ]; do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
