#!/usr/bin/env bash
# Displays numbers from 1 to 20 and do the following
# Displays "4" and then "bad luck from china" for the 4th loop iteration
# displays "9" and then "bad luck from japan" for the 9th loop iteration
# displays "17" and then "bad luck from italy'" for the 17th loop iteration
i=1

while [ $i -le 20 ]; do
	echo "$i"
	case "$i" in
		4)
		    echo "bad luck from China" ;;
		9)
		    echo "bad luck from Japan" ;;
		17)
		    echo "bad luck from Italy" ;;
	esac
	i=$((i+1))
done
