#!/usr/bin/env/bash
# change localhost IP adress
cp /etc/hosts /etc/hosts.old
sed -i "s/^127[0-9.]*\slocalhost/127.0.0.2 localhost/" /etc/hosts
sed -i "$ a\8.8.8.8 facebook.com" /etc/hosts
cp -f /etc/hosts /etc/hosts.old
